default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5433
  username: postgres
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: globalmedia2025reparada

test:
  <<: *default
  database: global2025reparada

production:
  <<: *default
  database: globalmedia2025reparada
